from typing import Protocol

from packages.characters.models import CharacterCreate, CharacterRead, CharacterUpdate


class CharacterRepository(Protocol):
    def create(self, series_id: str, payload: CharacterCreate) -> CharacterRead: ...

    def list_for_series(self, series_id: str) -> list[CharacterRead]: ...

    def get(self, character_id: str) -> CharacterRead | None: ...

    def update(self, character_id: str, payload: CharacterUpdate) -> CharacterRead | None: ...

    def name_exists(self, series_id: str, name: str, exclude_id: str | None = None) -> bool: ...
